GigGo/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from GigGo_App.views import *
from GigGo_App import urls as giggo_urls


app_name = 'GigGo_App'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(giggo_urls, namespace='GigGo_App')),

]

GigGo_App/urls.py
from django.urls import path, reverse_lazy
from GigGo_App.views import *
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'GigGo_App'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('register/', SignUpView.as_view(), name='signup'),
    path('poster/dashboard/', UserDashboardView.as_view(), name='poster_dashboard'),
    path('login/', LoginView.as_view(template_name="signin.html", next_page=reverse_lazy('GigGo_App:dashboard')), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('GigGo_App:login')), name='logout'),

    path('finder/', FinderHomeView.as_view(), name='finder_index'),
    path('finder/dashboard/', FinderDashboardView.as_view(), name='finder_dash'),
    path('finder/applications/', ApplicationListView.as_view(), name='finder_applications'),
    path('finder/apply/<int:id>/', ApplyJobView.as_view(), name='finder_apply'),

    path('search/', SearchView, name='search'),

    path('poster/createjob/', CreateJobView.as_view(), name='poster_createjob'),
    path('poster/joblist/', JobListView.as_view(), name='poster_joblist'),
    path('poster/updatejob/<int:pk>/', UpdateJobView.as_view(), name='poster_updatejob'),
    path('poster/deletejob/<int:pk>/', DeleteJobView.as_view(), name='poster_deletejob'),


]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>GigGo Platform</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon/favicon-32x32.png' %}" rel="icon">
    <link href="{% static 'assets/img/favicon/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    {% block stylesheet %}
    {% endblock stylesheet %}
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-top">
        <div class="container">
            <div class="header-container d-flex align-items-top justify-content-between">
                <div class="logo">
                    <h1 class="text-light"><a href="{% url 'GigGo_App:index' %}"><span>GigGo</span></a></h1>
                    <!-- Uncomment below if you prefer to use an image logo -->
                    <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
                </div>

                <nav id="navbar" class="navbar">
                    <ul>
                        <li><a class="nav-link scrollto active" href="{% url 'GigGo_App:index' %}">Home</a></li>
                        <!-- <li><a class="nav-link scrollto" href="#about">Categories</a></li> -->
                        <li><a class="nav-link scrollto" href="{% url 'GigGo_App:index' %}#why-us">About Us</a></li>
                        <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                        <li><a class="getstarted scrollto" href="{% url 'GigGo_App:signup' %}">Get Started</a></li>
                    </ul>
                    <i class="bi bi-list mobile-nav-toggle"></i>
                </nav><!-- .navbar -->

            </div><!-- End Header Container -->
        </div>
    </header><!-- End Header -->

    {% block hero %}
    {% endblock hero %}

    {% block main %}
    {% endblock main %}

    {% block contacts %}
        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4" data-aos="fade-right">
                        <div class="section-title">
                            <h2>Contact</h2>
                        </div>
                    </div>
        
                    <div class="col-lg-8" data-aos="fade-up" data-aos-delay="100">
                        <iframe
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.6294310367985!2d39.28578761428516!3d-6.814846568549566!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x185c4b0e4816b04b%3A0x41097d819dc4a5d9!2sAzikiwe%20St%2C%20Dar%20es%20Salaam!5e0!3m2!1sen!2stz!4v1672872846716!5m2!1sen!2stz"
                            width="100%" style="border:0; height:270px;" allowfullscreen="" loading="lazy"
                            referrerpolicy="no-referrer-when-downgrade" frameborder="0"></iframe>
                        <div class="info mt-4">
                            <i class="bi bi-geo-alt"></i>
                            <h4>Location:</h4>
                            <p>A108 Azikiwe Street, Dar Es Salaam, Dsm, Tanzania</p>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 mt-4">
                                <div class="info">
                                    <i class="bi bi-envelope"></i>
                                    <h4>Email:</h4>
                                    <p>info@giggo.com</p>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="info w-100 mt-4">
                                    <i class="bi bi-phone"></i>
                                    <h4>Call:</h4>
                                    <p>+255 738 999 000</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        
            </div>
        </section><!-- End Contact Section -->
    {% endblock contacts %}
    
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-top text-md-start">
                <div class="copyright">
                    &copy; <script>document.write(new Date().getFullYear());</script> Copyright <strong><span>GigGo</span></strong>. All Rights Reserved.
                </div>
                <!-- <div class="credits">
          Designed by <a href="https://github.com/e-ManueI">e-Manuel</a>
        </div> -->
            </div>
            <div class="social-links text-top text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

templates/createjob.html
{% extends 'base.html' %}

{% load static %}

{% block main %}
<main id="main">
    <div class="container">
    {{form.as_p}}
    </div>
</main>
{% endblock main %}

templates/finder_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard - GigGo</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon/favicon-32x32.png' %}" rel="icon">
    <link href="{% static 'assets/img/favicon/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/userprofile_style.css' %}" rel="stylesheet">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="{% url 'GigGo_App:index' %}" class="logo d-flex align-items-center">
                <img src="{% static 'assets/img/favicon/favicon-32x32.png' %}" alt="">
                <span class="d-none d-lg-block">GigGo - Finder</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->


        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">{{user.username}}</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{user.first_name}} {{user.last_name}}</h6>
                            <span>{{user.job}}</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'GigGo_App:logout' %}">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'GigGo_App:finder_dash' %}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            {% comment %} <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'GigGo_App:poster_createjob' %}">
                    <i class="bi bi-plus-square"></i>
                    <span>Post Gig</span>
                </a>
            </li> {% endcomment %}
            <!-- End Create Gigs Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'GigGo_App:finder_applications' %}">
                    <i class="bi bi-card-checklist"></i>
                    <span>Applied Gigs</span>
                </a> 
            </li>
            <!-- End Complaints Nav -->

            <li class="nav-heading">
                <hr>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->
        </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">
        
        {% block dash_title %}
        <div class="pagetitle">
            <h1>Dashboard</h1>
        </div><!-- End Page Title -->
        {% endblock dash_title %}

        <!-- Show messages -->
        {% if messages %}
        <div class="alert-banner text-center">
            {% for message in messages %}
            <div id="alert-{{ forloop.counter }}" class="alert alert-{{ message.tags }} alert-dismissible fade show"
                role="alert" class="alerts">
                {{ message }}
            </div>
            <script>
                setTimeout(function () {
                    $('#alert-{{ forloop.counter }}').fadeOut('slow');
                }, 8000);
            </script>
            {% endfor %}
        </div>
        {% endif %}
        <!-- end show messages  -->

        
        {% block content %}

        {% endblock content %}


    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer fixed-bottom">
        <div class="copyright">
            &copy;  <script>document.write(new Date().getFullYear());</script> Copyright <strong><span>GigGo</span></strong>. All Rights Reserved
        </div>

    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/userprofile_main.js' %}"></script>

</body>

</html>

templates/joblist.html
{% for job in object_list %}
    {{ job.name }}
{% endfor %}

templates/poster_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard - GigGo</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon/favicon-32x32.png' %}" rel="icon">
    <link href="{% static 'assets/img/favicon/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">
    {% block stylesheet %}{% endblock stylesheet %}
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/userprofile_style.css' %}" rel="stylesheet">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="{% url 'GigGo_App:index' %}" class="logo d-flex align-items-center">
                <img src="{% static 'assets/img/favicon/favicon-32x32.png' %}" alt="">
                <span class="d-none d-lg-block">GigGo - Hire</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->


        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">{{user.username}}</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{user.first_name}} {{user.last_name}}</h6>
                            <span>{{user.job}}</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'GigGo_App:logout' %}">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'GigGo_App:poster_dashboard' %}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'GigGo_App:poster_createjob' %}">
                    <i class="bi bi-plus-square"></i>
                    <span>Post Gig</span>
                </a>
            </li>
            <!-- End Create Gigs Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'GigGo_App:poster_joblist' %}">
                    <i class="bi bi-card-checklist"></i>
                    <span>Gig List</span>
                </a>
            </li>
            <!-- End Complaints Nav -->

            <li class="nav-heading">
                <hr>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->
        </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">
        
        {% block dash_title %}
        <div class="pagetitle">
            <h1>Dashboard</h1>
        </div><!-- End Page Title -->
        {% endblock dash_title %}

        <!-- Show messages -->
        {% if messages %}
        <div class="alert-banner text-center">
            {% for message in messages %}
            <div id="alert-{{ forloop.counter }}" class="alert alert-{{ message.tags }} alert-dismissible fade show"
                role="alert" class="alerts">
                {{ message }}
            </div>
            <script>
                setTimeout(function () {
                    $('#alert-{{ forloop.counter }}').fadeOut('slow');
                }, 8000);
            </script>
            {% endfor %}
        </div>
        {% endif %}
        <!-- end show messages  -->

        
        {% block content %}

        {% endblock content %}


    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer fixed-bottom">
        <div class="copyright">
            &copy;  <script>document.write(new Date().getFullYear());</script> Copyright <strong><span>GigGo</span></strong>. All Rights Reserved
        </div>

    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/userprofile_main.js' %}"></script>

</body>

</html>

templates/poster_createjob.html
{% extends 'poster_base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'assets/css/post-Form.css' %}">
{% endblock stylesheet %}

{% block dash_title %}{% endblock dash_title %}
{% block content %}

    <section class="inner-page">
        <div class="container">
            <!-- Start: Registration Form with Photo -->
            <section class="login-clean">
                <form method="post">
                    {% csrf_token %}

                    <div class="illustration">
                        <h3>Post A Job</h3>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                {{ form.category }}
                                
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                              {{ form.location }}
                            
                                {% comment %} <input class="form-control" name="location" placeholder="location"> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                {{ form.price }}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        {{ form.description }}
                    </div>
                 
            
                    <!-- <input class="check" type="checkbox"><small class="form-text">Remember me</small> -->
                    <div class="mb-3">
                        <input type="submit" class="btn btn-primary d-block w-50 center">
                    </div>
                    
                </form>
            </section>
        </div>
    </section>

<!-- End #main -->
{% endblock content %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'assets/css/Login-Form-Clean.css' %}">
{% endblock stylesheet %}

{% block main %}
<main id="main">
    <section class="inner-page">
        <div class="container">
            <!-- Start: Registration Form with Photo -->
            <section class="login-clean">
                <form method="post">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <div class="illustration">
                        <h3>Sign In</h3>
                    </div>
                    <div class="mb-3">
                        <input class="form-control" name="username" placeholder="username">
                    </div>
                    <div class="d-lg-flex align-items-lg-center mb-3">
                        <input class="form-control" name="password" placeholder="Password">
                        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"
                            fill="none">
                            <path
                                d="M13.8749 18.8246C13.2677 18.9398 12.6411 19 12.0005 19C7.52281 19 3.73251 16.0571 2.45825 12C2.80515 10.8955 3.33851 9.87361 4.02143 8.97118M9.87868 9.87868C10.4216 9.33579 11.1716 9 12 9C13.6569 9 15 10.3431 15 12C15 12.8284 14.6642 13.5784 14.1213 14.1213M9.87868 9.87868L14.1213 14.1213M9.87868 9.87868L6.58916 6.58916M14.1213 14.1213L17.4112 17.4112M3 3L6.58916 6.58916M6.58916 6.58916C8.14898 5.58354 10.0066 5 12.0004 5C16.4781 5 20.2684 7.94291 21.5426 12C20.8357 14.2507 19.3545 16.1585 17.4112 17.4112M17.4112 17.4112L21 21"
                                stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round"></path>
                        </svg> -->
                    </div>
                    <!-- <input class="check" type="checkbox"><small class="form-text">Remember me</small> -->
                    <div class="mb-3">
                        <input type="submit" class="btn btn-primary d-block w-50 center">
                    </div>
                    <a class="forgot" href="{% url 'GigGo_App:signup' %}">You don't have account? <strong>Sign Up</strong></a>
                </form>
            </section>
        </div>
    </section>
</main>
<!-- End #main -->
{% endblock main %}

templates/updatejob.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>